### ISSUE TITLE
Code Cleanup!

### ISSUE THREAD

**Issue by roerohan** [roerohan/Miscellaneous#1]
Clean-up bad code wherever you find in the repository.

**Comment by MounicaChanda0809** [comment]
Can I work on this?

**Comment by roerohan** [comment]
Yeah, sure.

**Comment by MounicaChanda0809** [comment]
Sorry! I thought it's an Android project.

**Comment by roerohan** [comment]
If you're looking for an Android Project, you may checkout
https://github.com/roerohan/Juvo-App/issues/1 .

**Comment by MounicaChanda0809** [comment]
Thanks a lot!

**Comment by roerohan** [comment]
You're welcome @MonicaChanda0809!

**Comment by roerohan** [comment]
Thanks @matthewcm
